// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxjtgiunlesbretadnft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4anRnaXVubGVzYnJldGFkbmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTg2NjEsImV4cCI6MjA2OTQ3NDY2MX0.knWZegfz-pO6AydcwGSsdc44K7Vyju-GqnGBaTXdVk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});